const express = require('express')
const router = express.Router()

const users = require('./users')
const pengabdian = require('./pengabdian')
const penelitian = require('./penelitian')
const anggotaPenelitian = require('./anggotaPenelitian')
const catatanHarian = require('./catatanHarian')
const reviewerPenelitian = require('./reviewerPenelitian')
const penJadwalan = require('./penjadwalan')
const jurusan = require('./jurusan')
const prodi = require('./prodi')
const revisiPenelitian = require('./revisiPenelitian')
const dokumenPenelitian = require('./dokumenPenelitian')
const laporanKemajuan = require('./laporan')
const nilaiUsulan = require('./nilaiUsulan')

router.use('/users', users)
router.use('/penelitian', penelitian)
router.use('/pengabdian', pengabdian)
router.use('/reviewerPenelitian', reviewerPenelitian)
router.use('/anggotaPenelitian', anggotaPenelitian)
router.use('/catatanHarian', catatanHarian)
router.use('/penJadwalan', penJadwalan)
router.use('/jurusan', jurusan)
router.use('/prodi', prodi)
router.use('/revisiPenelitian', revisiPenelitian)
router.use('/dokumenPenelitian', dokumenPenelitian)
router.use('/laporan', laporanKemajuan)
router.use('/nilaiUsulan', nilaiUsulan)

module.exports = router